# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user1 = User.create(user_name: "seanperfecto")
user2 = User.create(user_name: "ericadams")
user3 = User.create(user_name: "prettyprincess69")
user4 = User.create(user_name: "yungthug22")
user5 = User.create(user_name: "sanfransux")

poll1 = Poll.create(title: "Sport Culture In America", author_id: 1)
poll2 = Poll.create(title: "West Coast vs. East Coast", author_id: 2)
poll3 = Poll.create(title: "Dress Codes in Middle School", author_id: 3)

question1 = Question.create(qtext: "Quick question: Who be ballin?", poll_id: 1)
question2 = Question.create(qtext: "Quick question: Who not ballin?", poll_id: 1)
question3 = Question.create(qtext: "Best in the East?", poll_id: 2)
question4 = Question.create(qtext: "Best in the West?", poll_id: 2)
question5 = Question.create(qtext: "How short is too short?", poll_id: 3)
question6 = Question.create(qtext: "Why won't he talk to me?", poll_id: 3)

ac1 = AnswerChoice.create(actext: "Sean Perfecto", question_id: 1)
ac2 = AnswerChoice.create(actext: "Eric Adams", question_id: 1)
ac3 = AnswerChoice.create(actext: "Kobe Bryant", question_id: 1)
ac4 = AnswerChoice.create(actext: "Kim Jong Un", question_id: 2)
ac5 = AnswerChoice.create(actext: "Vladamir Putin", question_id: 2)
ac6 = AnswerChoice.create(actext: "New York City", question_id: 3)
ac7 = AnswerChoice.create(actext: "Boston", question_id: 3)
ac8 = AnswerChoice.create(actext: "Philadelphia", question_id: 3)
ac9 = AnswerChoice.create(actext: "Baltimore", question_id: 3)
ac10 = AnswerChoice.create(actext: "Los Angeles", question_id: 4)
ac11 = AnswerChoice.create(actext: "San Francisco", question_id: 4)
ac12 = AnswerChoice.create(actext: "San Diego", question_id: 4)
ac13 = AnswerChoice.create(actext: "Portland", question_id: 4)
ac14 = AnswerChoice.create(actext: "Nothing", question_id: 5)
ac15 = AnswerChoice.create(actext: "Above the knee", question_id: 5)
ac16 = AnswerChoice.create(actext: "Above the ankle", question_id: 5)
ac17 = AnswerChoice.create(actext: "There is no limit", question_id: 5)
ac18 = AnswerChoice.create(actext: "He's crazy", question_id: 6)
ac19 = AnswerChoice.create(actext: "I'm too hot", question_id: 6)
ac20 = AnswerChoice.create(actext: "He's not real", question_id: 6)
ac21 = AnswerChoice.create(actext: "All of the above", question_id: 6)

resp1 = Response.create(user_id: 1, answer_choice_id: 1)
resp2 = Response.create(user_id: 1, answer_choice_id: 4)
resp3 = Response.create(user_id: 1, answer_choice_id: 6)
resp4 = Response.create(user_id: 1, answer_choice_id: 10)
resp5 = Response.create(user_id: 1, answer_choice_id: 15)
resp6 = Response.create(user_id: 1, answer_choice_id: 19)
resp7 = Response.create(user_id: 2, answer_choice_id: 2)
resp8 = Response.create(user_id: 2, answer_choice_id: 4)
resp9 = Response.create(user_id: 2, answer_choice_id: 9)
resp10 = Response.create(user_id: 2, answer_choice_id: 12)
resp11 = Response.create(user_id: 2, answer_choice_id: 16)
resp12 = Response.create(user_id: 2, answer_choice_id: 20)
resp13 = Response.create(user_id: 3, answer_choice_id: 3)
resp14 = Response.create(user_id: 3, answer_choice_id: 5)
resp15 = Response.create(user_id: 3, answer_choice_id: 6)
resp16 = Response.create(user_id: 3, answer_choice_id: 13)
resp17 = Response.create(user_id: 3, answer_choice_id: 14)
resp18 = Response.create(user_id: 3, answer_choice_id: 21)
resp19 = Response.create(user_id: 4, answer_choice_id: 3)
resp20 = Response.create(user_id: 4, answer_choice_id: 5)
resp21 = Response.create(user_id: 4, answer_choice_id: 8)
resp22 = Response.create(user_id: 4, answer_choice_id: 10)
resp23 = Response.create(user_id: 4, answer_choice_id: 14)
resp24 = Response.create(user_id: 4, answer_choice_id: 18)
resp25 = Response.create(user_id: 5, answer_choice_id: 3)
resp26 = Response.create(user_id: 5, answer_choice_id: 4)
resp27 = Response.create(user_id: 5, answer_choice_id: 9)
resp28 = Response.create(user_id: 5, answer_choice_id: 11)
resp29 = Response.create(user_id: 5, answer_choice_id: 16)
resp30 = Response.create(user_id: 5, answer_choice_id: 21)
#resp31
